Do:
  you:
    - recycle
    - have:
      - a:
        - nickname
      - any:
        - siblings
        - pets
    - like:
      - social networks
      - muffins
      - video games
      - the:
        - city:
          - or:
            - country
          - where you:
            - live
      - to:
        - travel
        - sing out loud when no one else is around
    - want:
      - old times back
      - to know more:
          about:
            - your:
              - future
              - relatives
            - history
            - new inventions
      - more:
        - money
        - friends
        - things than you need
    - think that:
        - late is better than never
    - prefer:
        to:
          - take baths or showers
  your:
    friends:
      like:
        - you:
          - the way you are
        - social networks
        - muffins
        - video games
      know:
        [much, too much]:
          about:
            - your:
              - life
              - hobbies
              - family
              - friends
            - you
What:
  - was:
      the:
        best:
          - day of your life like
        last:
          - concert you've been to
          - song:
              - you listened on repeat
          - thing:
              you:
                have:
                  - bought
                  - done
                  - eaten
      your:
        favourite:
          song:
            - as a 5 year old
            - from a few weeks ago
  - would:
      you:
        do:
          if:
            you:
              had:
                - one million dollars
                - the ability to fly
              were:
                - a dragon
              woke up:
                with:
                  - someone else next to you
                  - some drawings in your face
  - do:
      you:
        do:
          - for fun
          - 'on':
            - the:
              - weekend
        usually:
          - do when you're bored
          - have for breakfast
        like:
          more,:
            - dogs or cats
            - shower or bath
            - tea or coffee
        think:
          about:
            - the:
              - Internet
            - Bad Dragon
            - dragons
            - '"fact" accounts'
            - society
            - cats
            - surveillance
            - coyotes
            - raccoons
            - foxes
            - dogs
            - lizards
  - [activity, activities]:
      do:
        you:
          - enjoy the most
  - kind:
      of:
        animals:
          - do you have
  - habit:
      do:
        you:
          really:
            find:
              cute:
                - in a person
  - is:
      your:
        - first memory
        - dream job
        - favourite:
          - activity
          - animal
          - beverage
          - board game
          - book series
          - console
          - food
          - Internet browser
          - language
          - name
          - number
          - piece of music
          - programming language
          - season
          - snack
          - sports team
          - type of cheese
          - video game
          - way to eat a potato
          - website
      the:
        [best, worst]:
          thing:
            - about:
                - society
                - the:
                    - Internet
                - your:
                    - favourite:
                      - series
                      - movie
                      - book
                    - country
                    - hometown
            - one can do:
              - if:
                - "they're bored"
            - ever
          fast:
            food:
              - chain
          way:
            - to prepare and eat eggs
      one:
        - thing you would like to become better at
  - was:
      the:
        last:
          thing:
            you:
              - did
              - ate
              - looked for
        [best, worst]:
          thing:
            - "you've eaten so far"
  - languages do you know
  - apps do you use daily
  - 'is heavier: a kilogram of steel, or a kilogram of feathers'
Can:
  you:
    - swim
    - speak:
      - different:
        - languages
    - play:
      - any:
        - sports
      - the:
        - piano
        - guitar
        - trumpet
        - saxophone
      - baseball
    - ski
    - cook
    - dance
    - yodel
    - draw
Are:
  you:
    - religious
Have:
  you:
    ever:
      - been:
        - to:
          - Austria
          - Germany
          - Japan
          - Switzerland
          - France
          - Sweden
          - Norway
          - Finland
          - Australia
          - Italy
          - Russia
          - China
          - the:
            - USA
            - United Kingdom
        - caught:
          - "doing things you shouldn't do"
          - cheating
        - mistaken for:
          - someone else
      - listened to:
        - classical music
        - drum and bass
        - dubstep
        - frenchcore
        - hardstyle
        - J-Pop
        - K-Pop
        - metal
        - music:
          - "from the 50's"
          - "from the 60's"
          - "from the 70's"
          - "from the 80's"
          - "from the 90's"
        - nightcore
        - punk rock
        - trance
        - vaporwave
      - had:
        - an:
          - accident
      - pet:
        - a bat
        - a bnuuy
        - a bunny
        - a cat
        - a coyote
        - a dog
        - a dragon
        - a ferret
        - a fox
        - a horse
        - a hyena
        - a lion
        - a lizard
        - a marten
        - a mouse
        - a raccoon
        - a rat
        - a shark
        - a wolf
        - an opossum
        - an otter
        - an owl
      - ridden a horse
      - written:
        - a love letter
        - code
        - in Japanese
How:
  fast:
    - are you
    - is your internet connection
  has:
    your:
      day:
        - been
  often:
    do you:
      - cook
      - eat food not prepared by yourself
      - iron your clothes
      - take selfies
      - use condiments
  old:
    are:
      - you
  many:
    - open tabs do you currently have
    - followers is too many
Where:
  do:
    you:
      - work
      - live
Which:
  food:
    do:
      you:
        - love
        - hate
Who:
  is:
    the:
      - most famous person you have met
    your:
      - favourite:
        - Retrospring user
        - actor
        - artist
        - comedian
        - musician
Why:
  do:
    - they call it oven when you of in the cold food of out hot eat the food
Would:
  you:
    rather:
      live:
        - in:
          - a city or in the countryside
          - a flat or in a house
      lose:
        - an arm or a leg
      be:
        - the best player on a horrible team or the worst player on a great team
